### PR TITLE
Merge pull request #19 from ncss/master

### PR DESCRIPTION
**Pull request by Jackywathy**
merging master into dev (mostly readme.md)

### CODE REVIEW

**Comment by Jackywathy** [comment]
oops i was meant to pull master into dev

**Comment by tracey-le** [comment]
hehe that's okay :) I don't think it changed anything anyway though, but is it possible to undo/revert things like pull requests?

**Comment by juliawong** [comment]
@t1-tracey Yes there is! :) I usually Google for this but it looks like GitHub has a button for you to click https://help.github.com/articles/reverting-a-pull-request/

As this PR is closed, there is no need to do anything else.

**Comment by tracey-le** [comment]
ooh that's really helpful, thanks @juliawong :D

**Pull request closed without merging**
