### PR TITLE
cloning-instructions

### PR DESCRIPTION
**Pull request by tracey-le**
Adding how to run the project in README.md

The images are a bit big and some of the spacing is off but here is the
edited draft from https://github.com/ncss/projects-2017-3/issues/14

### CODE REVIEW

**Comment by t1-tracey** [comment]
Will the tutors be able to do the pull request for the latest version of the branch `pr/15`?

**Comment by juliawong** [comment]
@t1-tracey Merged #15 

Tip: if you want to link to a PR or an issue in a comment, just type # and then the number.

**Comment by t1-tracey** [comment]
ooh okay thank you for the tip @juliawong 😄 that will make it a lot easier :)

thank you for all the merging! ☺️

**Comment by t1-tracey** [comment]
@juliawong do you think you would be able to do the pull requests for #17 (this one on README.md, I added onto #15) and #16 (it has the live error messages)? 😊

**Comment by juliawong** [comment]
I'm currently out but perhaps @liamcal or @ekohilas can help. Otherwise I'll take a look when I get back tonight.

So awesome to see you keep working on the project! :D

**Comment by t1-tracey** [comment]
oh sorry, don't worry that's okay 😊

I'm so glad to get to still get in touch with you guys 😄😊

**Comment by juliawong** [comment]
No need to apologise! :) If none of us get around to it feel free to message us here or on FB.

**Review by juliawong — APPROVED** [review]

**Comment by t1-tracey** [comment]
Thank you so much Julia! 😃😄

**Comment by tracey-le** [comment]
@lyneca do we still need this branch `pr/15` (the how-to for README.md)? we were thinking about deleting a few branches to reduce confusion for #24. but of course always okay to leave this! :D

**Pull request merged**
