### PR TITLE
Signup validation test

### PR DESCRIPTION
**Pull request by t1-tracey**
Im putting in Jack’s changes manually ^_^
JIT validation doesn’t work right now unfortunately with changes :(

### CODE REVIEW

**Comment by t1-tracey** [comment]
I don't know what I'm doing oh dear

**Comment by ninjaprawn** [comment]
Seriously does anyone?

**Comment by t1-tracey** [comment]
woah didn't know there were emojis!

Hehe, hold on, just gonna try sort this out and add all the changes back in...

**Comment by Jackywathy** [comment]
Well it looks like theres no conflicts

**Comment by t1-tracey** [comment]
Hehe, actually it turns out because I was trying to resolve it in the web editor but I don't think I was looking closely and just marked it as resolved. Then opened the files again and saw duplicate lines and stuff missing ahh 😆

**Comment by t1-tracey** [comment]
Okay, I think this should be okay now 😊🤞

What I found interesting and got me thinking about this in the first place :)
https://blog.codinghorror.com/the-just-in-time-theory/

**Comment by t1-tracey** [comment]
Wow that's pretty awesome :O 

Now I see how you can branch off, go and try something, and then bring it in. Hehe did run into a few troubles with merge conflicts, but it was just a little frustrating and fun at the same time :) it's pretty satisfying for some reason, just seeing that message saying the pull request was merged successfully 😂 

Thanks so much again to everyone <3 and to @lbain for the lovely version control intro and helping with my questions afterwards :D

**Comment by t1-tracey** [comment]
What happens when the branch is deleted? It says it can be 'safely deleted', which I suppose means it won't affect what's in `dev` if I delete it. 

But does it mean I won't be able to access the changes made throughout this branch any more? I would like to still be able to see those as a record so I think I will leave them in for now. Or maybe they get included inside `dev` too anyway? 🤔

**Comment by juliawong** [comment]
@t1-tracey when the branch is deleted you won't be able to work on it anymore or see it. 

As you've merged this branch into dev already, deleting it won't affect the dev branch. If you want to view what changes a branch made, you can view the commit which merges it in. e.g. 484fd29

You don't have to delete branches once you're done with them, you can always leave them. :) However over time you may find that you've got lots and lots of branches so you may want to delete some to clean it up.

**Comment by t1-tracey** [comment]
oohh, okay, thank you so much @juliawong that's really helpful 😄😄😄 that answers everything :D

**Pull request merged**
